source_language = "C++"
include_defines = [
]
using_namespaces = [
    {used = "A", parent = ""},
    {used = "C", parent = ""},
]
direct_includes = [
]
local_code_path = "add_namespace_qualifier.ii"
