local_header_patterns = ["**simple_inline_header.hh"]
local_type_patterns = ["pattern_local_type::OnlyLocalType"]
pure_c_header_patterns = ["**pure_c_api.h"]
include_defines = ["DEFINE_A", "DEFINE_B"]
