source_language = "C++"
include_defines = [
]
direct_includes = [
    {is_system_header = false, path = "<REPO_DIR>/test_local_code/included_static_function.hh"},
]
local_code_path = "included_static_function.ii"
