source_language = "C++"
include_defines = [
]
direct_includes = [
    {is_system_header = false, path = "<REPO_DIR>/test_local_code/out_of_line_nested_type_method.hh"},
]
local_code_path = "out_of_line_nested_type_method.ii"
