[package]
name = "ccelerate_wrappers"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
ccelerate_shared = { path = "../ccelerate_shared" }
anyhow = "1.0.96"
